### ISSUE TITLE
rultor should not be included as contributor

### ISSUE THREAD

**Issue by Mariatta** [coala/landing-frontend#129]

**Comment by sils** [comment]
why? I'm not sure we want special handling here.

**Comment by sils** [comment]
we may want to have a mixed score of reviews and commits to reward both I guess

**Comment by Mariatta** [comment]
Cause it's not a real person...

**Comment by Mariatta** [comment]
And maybe gitmate should be excluded too... can't compete with a bot.. :sweat_smile:
