### ISSUE TITLE
Improve responsiveness in bear details view

### ISSUE THREAD

**Issue by hemangsk** [coala/landing-frontend#137]
- [ ]  Links move out of the container

- [ ]  Bear name font size is too large in small screen (should decrease responsively and responsibly 😉  )
<img src="https://cloud.githubusercontent.com/assets/13018570/22725135/3dda1574-edf1-11e6-8404-97d168e2374b.png" height=200 />

**Comment by meetmangukiya** [comment]
Could we make the two colums to two rows on small screen? That'd be better I think

**Comment by hemangsk** [comment]
@meetmangukiya have a look, this keeps intact the columnish look as well
<img src="https://cloud.githubusercontent.com/assets/13018570/22725547/2545116e-edf4-11e6-96d6-5c914e81ff19.png" height=200 />
