### ISSUE TITLE
UI Mockup for the coala Online Module

### ISSUE THREAD

**Issue by hemangsk** [coala/landing-frontend#170]
Hey coalians 😃 

During GSoC phase 2, I will work on creating the frontend for coala Online Module. 
The coala Online module is basically an upgrade of the current Try Online module, so that bears with non optional settings can be used and result is returned.

Also,
-  Incase of any kind of errors encountered, for example while receiving results in frontend or while making request to backend to run coala, a relevant error message is shown rather than a standard message like being done presently. 
- Validation exists for user input, for example, while asking users for max_line_length setting, the input can only be an integer. If any other data type is entered, then a error message is displayed showing the expected input type and given input type.
- Take link of GitHub repository and do analysis

This frontend module will add interactivity to these features. For the frontend of coala Online, it'd be really really helpful if we can incorporate new ideas from community. I’ve designed some UI components which will definitely go in the layout, and these include, 

- A tab interface to switch between Instant and Repository mode.
- Using Materialize CSS’s Switch, Range  and General Input Box  for taking user input.  

Let me know your thoughts if there's more functionality we can add/remove and in what ways we can improve the layout. 

![2pdf](https://cloud.githubusercontent.com/assets/13018570/26322315/126e18ec-3f48-11e7-9ba7-9246a988c710.png)

**Comment by sils** [comment]
didn't we want to use coala-html embedded here?

**Comment by hemangsk** [comment]
Yea. This has some additional functionality as well like it has options to choose bears and run coala on code on button click.
 We can use the coala-html's result displaying functionalities, that is its front end part.

**Comment by hemangsk** [comment]
Completed via https://github.com/coala/landing-frontend/pull/206, https://github.com/coala/landing-frontend/pull/180, https://github.com/coala/landing-frontend/pull/187
