### ISSUE TITLE
coalaOnline: Text goes out of container in cases when coafiles has a lot of bears

### ISSUE THREAD

**Issue by hemangsk** [coala/landing-frontend#189]
Changes should be done at https://github.com/coala/coalaCSS
![screen shot 2017-07-01 at 5 43 58 am](https://user-images.githubusercontent.com/13018570/27757554-7307cd5a-5e20-11e7-96a7-968f0a88c779.png)

**Comment by raghavmittal101** [comment]
Can I fix this issue?

**Comment by khanchi97** [comment]
Hello @raghavmittal101 !!
According to http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html
I think you should start shortlog of your commit with a capital letter.
