### ISSUE TITLE
tabs.html in partials seems to be redundant

### ISSUE THREAD

**Issue by sils** [coala/landing-frontend#19]
@hemangsk can it be deleted?

**Comment by hemangsk** [comment]
yeah it can be deleted without breaking any linking.

**Comment by SiddharthKumar02** [comment]
@sils should i be deleting the templateUrl /partials/tabs/home.html ?

**Comment by sils** [comment]
why do you ask?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by SiddharthKumar02** [comment]
How do i ensure no linking is broken?

**Comment by hemangsk** [comment]
@SiddharthKumar02 You can deploy it locally and check if any 404 errors are coming in Firefox/Chrome Developer console
