### ISSUE TITLE
Unnecessary console.log in languagesDirective.js

### ISSUE THREAD

**Issue by co-robo** [coala/landing-frontend#200]
On line 56, there's an unneeded console log.
difficulty newcomer
Opened by @gureks at [gitter/coala/cobot-test](https://gitter.im/coala/cobot-test?at=597190641c8697534a45f739)

**Comment by rstein66** [comment]
[languagesDirective.js#L56](https://github.com/coala/landing-frontend/blob/master/resources/js/Directives/languagesDirective.js#L56)
