### ISSUE TITLE
Languages page: Non optional -> Mandatory

### ISSUE THREAD

**Issue by Makman2** [coala/landing-frontend#224]
"Mandatory" is shorter than "Non optional" and imo just sounds better :)

**Comment by akhil117** [comment]
Is the changes should be done in language.html?

**Comment by akhil117** [comment]
if languages.html it was showing conflict file after git push. Could you help please??

**Comment by Makman2** [comment]
You have to resolve the conflicts, seems you've used an older version of this repo. Please google how to do this 👍
