### ISSUE TITLE
Small  Typo in the landing page

### ISSUE THREAD

**Issue by vaibhavsingh97** [coala/landing-frontend#228]
`Coala Online` should be in all caps
#### Screenshot for the issue
![image](https://user-images.githubusercontent.com/8705386/31053509-707760ee-a68e-11e7-9965-d618787e8aff.png)

**Yes, I am interested to fix this issue**

**Comment by SanketDG** [comment]
You should try pasting `Coala Online` in gitter chat and see what happens :)

**Comment by vaibhavsingh97** [comment]
Closing since it's not an issue 😄
