### ISSUE TITLE
Allow clicking on language labels to filter

### ISSUE THREAD

**Issue by co-robo** [coala/landing-frontend#230]
Clicking on `C` should close the bear dialog and filter all bears that support C.
Opened by @adtac at [gitter/coala/coala](https://gitter.im/coala/coala?at=59d4b7dc01110b723175c78f)

**Comment by aashutoshrathi** [comment]
Can I work on this?

**Comment by naveentata** [comment]
I'd like to work on this, I have made the changes. However, I am unable to assign the issue can I send the PR?
