### ISSUE TITLE
Fix link to correctly point it to bears documentation

### ISSUE THREAD

**Issue by co-robo** [coala/landing-frontend#232]
Opened by @prnvdixit at [gitter/coala/coala](https://gitter.im/coala/coala?at=59df7e79b20c642429f38f5d)

**Comment by prnvdixit** [comment]
Currently the [link](https://github.com/coala/landing-frontend/blob/9e9262aa5f3f5021723d8246be89b2d67758cb0a/partials/tabs/about.html#L25) in about page points to http://coala.io/#!/languages, change it to point to https://coala.io/#/languages
