### ISSUE TITLE
Fix Indentation in the Project

### ISSUE THREAD

**Issue by yashovardhanagrawal** [coala/landing-frontend#242]
Most of the files in the project do not have the correct indentation on every line.

**Comment by yashovardhanagrawal** [comment]
difficulty/low

**Comment by Makman2** [comment]
Please don't close issues without a reason and duplicating them, rather ask a maintainer to edit them if necessary :+1:

**Comment by yashovardhanagrawal** [comment]
@Makman2 I thought asking corobo to make issues is the standard here mostly, as it also adds the labels, thats why I closed it.

will not duplicate issues from next time

**Comment by prnvdixit** [comment]
Not necessary ^^ - You can add the labels in the issue description (at the time of making the issue) as eg. "labels: difficulty/newcomer" and it is probable (if everything goes right 😉) that gitmate will do it for you. Either way, if it doesn't work - Just ask someone on gitter channel to add relevant labels 👍
