### ISSUE TITLE
people.html: Correct typo of div

### ISSUE THREAD

**Issue by co-robo** [coala/landing-frontend#244]
in `partials/tabs/people.html` 
there's a typo at line 32 & 33
`</dib>
</dib>`
is written instead of div
difficulty/newcomer
Opened by @yashovardhanagrawal at [Gitter](https://gitter.im/coala/coala?at=5a0a9539505b630c05dda7d9)

**Comment by yashovardhanagrawal** [comment]
label this initiatives/gci

**Comment by pareksha** [comment]
I am a newcomer. Can I work on this issue?

**Comment by yashovardhanagrawal** [comment]
great! just ask a maintainer on Gitter to assign you this task!
make sure to read coala.io/newcomer before starting to contribute here :smile:

**Comment by pareksha** [comment]
Sure, thankyou
