### ISSUE TITLE
Bookmarkable example on homepage

### ISSUE THREAD

**Issue by bekicot** [coala/landing-frontend#277]
Currently, when selecting to a language example, we have no way to bookmark it.

![image](https://user-images.githubusercontent.com/1826884/40415238-a83a84f6-5ea4-11e8-9b48-0967480c4c8d.png)

This can be done via adding a query parameter to the url after the selection.
and add
```
document.getElementById('example').scrollIntoView();
```
after adding id to the example's `div`

**Comment by bekicot** [comment]
@jayvdb If, you reconsider this as not a `newcomer`, please assign me this, as my other task currently waiting for approval / blocked.

**Comment by jayvdb** [comment]
@anstkras , sorry for the delay, yes, assigned to you

**Comment by Ishaan28malik** [comment]
is someone working on this?

**Comment by Ishaan28malik** [comment]
if not please assign me this
