### ISSUE TITLE
Make the year in the footer dynamic

### ISSUE THREAD

**Issue by srivama** [coala/landing-frontend#290]
The year in the footer of the website coala.io is set to 2017. Instead of changing it every year, it can be set to current year.

The file can be found [here](https://github.com/coala/landing-frontend/blob/master/includes/footer.html)

**Comment by Vaibhav911** [comment]
I would really like to work on this as my newcomer issue. Can someone assign me this? Thanks.

**Comment by srivama** [comment]
@Vaibhav911 You can ask a maintainer on our gitter channel to get the issue assigned :)
