### ISSUE TITLE
Animation effects of Tabs only change while going back from ABOUT section though the page changes

### ISSUE THREAD

**Issue by AkshJain99** [coala/landing-frontend#295]
refer https://github.com/coala/projects/issues/179
while changing tabs from about to others and then coming back through back button on browser works fine but if we see other section except ABOUT  then same problem is there as in refered issue

**Comment by AkshJain99** [comment]
@li-boxuan please assign me this issue i know the solution to this problem I have solved similar problem like this in projects repo

**Comment by naveentvelu** [comment]
@AkshJain99 Were you able to solve this without compromising the animation effect?

**Comment by AkshJain99** [comment]
animation effects like what @naveentvelu

**Comment by AkshJain99** [comment]
yes this is solved without compromising animation effect .

**Comment by naveentvelu** [comment]
> animation effects like what @naveentvelu
> can you please tell me?

The sliding effect of the indicator below the tab

**Comment by AkshJain99** [comment]
yes that is the only thing what need to be fixed in the issue right?

**Comment by naveentvelu** [comment]
Previously the tab indicator was not moving.
I was trying to figure out that by including some scripts which mode the tab indicator movement sudden and not smooth.
That's y i asked whether the movement of the indicator was animated or not.

**Comment by AkshJain99** [comment]
@naveentvelu  it is working fine now

**Comment by naveentvelu** [comment]
Cool @AkshJain99
