### ISSUE TITLE
coala.io is down!

### ISSUE THREAD

**Issue by abhishalya** [coala/landing-frontend#304]
coala.io is down from a couple of days.

cc. @sils @jayvdb

**Comment by sils** [comment]
I've pinged Fabian personally about it, he and the association are managing
the domain IIRC.

**Comment by sils** [comment]
Ok @fneu confirmed that the domain is active, it does point to cloudflare which points to solar.coala.io which is our digitalocean server and that seems to be unavailable. @yukiisbored that's under your maintenance, right?

**Comment by sils** [comment]
The server on digitalocean itself is at 46.101.245.76 and is shown online so the problem is probably something on the server.

**Comment by abhishalya** [comment]
Thank you all. It is fixed now :)
