### ISSUE TITLE
idea: A link to docs and release after title

### ISSUE THREAD

**Issue by hemangsk** [coala/landing-frontend#34]
For eg sth like
![screen shot 2017-01-21 at 11 59 29 pm](https://cloud.githubusercontent.com/assets/13018570/22176686/d52bb0dc-e035-11e6-97cc-a8b2f49c07d1.png)

**Comment by gkrishnan724** [comment]
Hi, I would like to work on this can you give more details? :)

**Comment by hemangsk** [comment]
We have a WIP coala.io landing page on http://new.coala.io,  
so it'd be great to have a link to docs, source and releases under the main 'coala' heading :)

**Comment by sils** [comment]
@gkrishnan724 please note that this is urgent, if you can't do this soon please let us do it instead.

**Comment by gkrishnan724** [comment]
What is Source? is it the github organisation link?

**Comment by sils** [comment]
it's the coala/coala repo: https://github.com/coala/coala/
