### ISSUE TITLE
Use monospaced font in getting started section under the home tab

### ISSUE THREAD

**Issue by brainst** [coala/landing-frontend#60]
difficulty/newcomer

**Comment by brainst** [comment]
@meetmangukiya

**Comment by sils** [comment]
@meetmangukiya assuming you filed this issue? There's monospaced font there, if this issue still applies please make a new one and consider giving a better explanation of this issue ;)

**Comment by meetmangukiya** [comment]
@sils sorry, it seems monospaced now, maybe my browser was acting wierd :(
