### ISSUE TITLE
Improve readability in GetInvolved Section 

### ISSUE THREAD

**Issue by hemangsk** [coala/landing-frontend#79]

**Comment by Shruti9520** [comment]
@hemangsk Can I work on this issue?

**Comment by hemangsk** [comment]
Hey, welcome to this project! To get started, goto the gitter and say hello. They'll add you to the org which will let us assign you to an issue!

**Comment by hemangsk** [comment]
[Gitter Room ](https://coala.io/chat)

**Comment by Shruti9520** [comment]
@hemangsk Thanks

**Comment by hemangsk** [comment]
@shruti9520 you can use the command ```cobot assign <issue-link>``` on the gitter chatroom to get assigned to issues.

**Comment by Shruti9520** [comment]
@hemangsk Can I now work on this issue?

**Comment by hemangsk** [comment]
@Shruti sure :+1: assigned you :)

**Comment by Shruti9520** [comment]
@hemangsk I changed the heading part as well as the links (it shows underline on hover).
Here is the screenshot-

![coala](https://cloud.githubusercontent.com/assets/20228417/22593869/99748490-ea46-11e6-870a-129fdc1d47f4.png)

**Comment by hemangsk** [comment]
@Shruti9520 can you make a PR, that'll help reviewers test the changes locally

**Comment by Shruti9520** [comment]
@hemangsk  Sure :)

**Comment by Shruti9520** [comment]
@hemangsk PR#99

**Comment by Shruti9520** [comment]
@hemangsk PR#100
