### ISSUE TITLE
Links below title are not proper in mobile view

### ISSUE THREAD

**Issue by gkrishnan724** [coala/landing-frontend#85]
![screenshot from 2017-02-01 18-36-47](https://cloud.githubusercontent.com/assets/21004514/22508159/bf9a004e-e8ae-11e6-90a2-63d6ebea3ed0.png)

**Comment by rahulkrishnan98** [comment]
@gkrishnan724 what changes are required.

**Comment by rstein66** [comment]
@gkrishnan724 , do you still have this problem?  

If so, 
* What do you mean by not proper? (*e.g.* Are all 3 broken?  Is 1 directing you to the wrong view?)
* Which OS & browser?

**Comment by hemangsk** [comment]
@rstein66 as in the screenshot the text "docs" , "source" and "chat" are going outside the grey coloured chip which should not be the case.

**Comment by rstein66** [comment]
@hemangsk Oh, got it; thanks for the clarification!

**Comment by atishey7** [comment]
Hello, I am new to open source as well as front end development. I want to work on this issue. Can you tell me what technology should I learn for the same and where should I start in the codebase for fixing this issue? Also I am unable to setup the project landing-frontend as mentioned in README.md as there's no SimpleHTTPServer file.

**Comment by jayvdb** [comment]
This issue seems stale!

@harshant please reassign yourself if you're still working on this.

(Powered by [GitMate.io](https://gitmate.io))

**Comment by bharatpurohit97** [comment]
please assign me this issue.
