### ISSUE TITLE
Make bears selectable in the "Try coala" section

### ISSUE THREAD

**Issue by adtac** [coala/landing-frontend#93]
We can't possibly expect the user to type in the bear name - they don't know anything whent they arrive at the landing page!

**Comment by Makman2** [comment]
We should also display a description what the bear does^^ We could just take the docstring^^

**Comment by adtac** [comment]
We could also suggest them a bear based on the language they're typing in the code area above.

If we have the language information, we could also add syntax highlighting, but that's not really a priority right now :P

**Comment by Mariatta** [comment]
Yes. At first it was not even obvious that PEP8Bear is in a textbox that you can edit.

I think we should add a label/description above the two textboxes:

eg:
Type in some code:
[Code textarea]

Enter comma separated bear names, eg "PEP8Bear, YapfBear":
[Bear textbox]

[Run coala button]
